# Generated by Django 4.0 on 2021-12-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_created_alter_note_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='update',
            new_name='updated',
        ),
    ]
